# Generated by Django 5.1.4 on 2025-02-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
