# Generated by Django 5.1.4 on 2025-02-10 08:59

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('unique_code', models.CharField(default=core.models.code_generator, editable=False, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Groupcompany',
        ),
    ]
