# Generated by Django 5.1.4 on 2025-02-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groupmail_delete_groupcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmail',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
