# Generated by Django 5.1.6 on 2025-02-25 04:38

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_user_alter_companylead_assign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companyemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('unique_code', models.CharField(default=core.models.code_generator, editable=False, max_length=255, unique=True)),
                ('is_premium', models.CharField(default='No', max_length=255)),
                ('status', models.CharField(default='Active', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
            ],
        ),
    ]
