# Generated by Django 5.1.4 on 2024-12-26 08:17

import report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_id', models.CharField(default=report.models.id_generator, editable=False, max_length=255, unique=True)),
                ('visitor_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_local_time', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_time_spent', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_visit_count', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_call_action', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_form_action', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_returning', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_browser_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_client_type', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_device_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_device_model', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_city', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_country', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('visitor_region', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
