# Generated by Django 5.1.6 on 2025-02-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitor',
            name='browser_configuration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitor',
            name='browser_engine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
