# Generated by Django 5.1.4 on 2025-01-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_visit_id_lead_visitor_id_lead_visitor_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='mobile',
            new_name='phone',
        ),
    ]
